--DIMENSIONS
RAW_WINDOW_WIDTH = 1280
RAW_WINDOW_HEIGHT = 720
WINDOW_SCALE = 0.9
WINDOW_WIDTH = RAW_WINDOW_WIDTH / WINDOW_SCALE
WINDOW_HEIGHT = RAW_WINDOW_HEIGHT / WINDOW_SCALE
WINDOW_WIDTH_CENTER = WINDOW_WIDTH / 2
WINDOW_HEIGHT_CENTER = WINDOW_HEIGHT / 2

--PLATFORM
PLATFORM_HEIGHT = 32
PLATFORM_WIDTH = 64